[package]
name = "spl-token"
version = "8.0.0"
description = "Solana Program Library Token"
authors = { workspace = true}
repository = { workspace = true}
license = { workspace = true}
edition = { workspace = true}

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.9"
bytemuck = "1.20.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-account-info = "2.2.0"
solana-cpi = "2.2.0"
solana-decode-error = "2.2.0"
solana-instruction = "2.2.0"
solana-msg = "2.2.0"
solana-program-entrypoint = "2.2.0"
solana-program-error = "2.2.0"
solana-program-memory = "2.2.0"
solana-program-option = "2.2.0"
solana-program-pack = "2.2.0"
solana-pubkey = { version = "2.2.0", features = ["bytemuck"] }
solana-rent = "2.2.0"
solana-sdk-ids = "2.2.0"
solana-sysvar = { version = "2.2.0", features = ["bincode"] }
thiserror = "2.0"

[dev-dependencies]
lazy_static = "1.5.0"
mollusk-svm = "0.1.0"
proptest = "1.5"
serial_test = "3.2.0"
solana-clock = "2.2.1"
solana-native-token = "2.2.1"
solana-sdk = "2.2.1"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[package.metadata.solana]
program-id = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
